### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Zacknpa100** [PssbleTrngle/MiscIssues#7]
a couple weapons are missing the textures all maces boomerangs and battleaxes are missing textures even though i have every mod needed or asked to have

**Comment by Darakudemion** [comment]
This is still an issue. Couldn't even find them in a past version.

**Comment by PssbleTrngle** [comment]
Hello, I’m sorry for not responding.
I’ll try to put some work into this as soon as possible to finally complete the mod

**Comment by ArdiPINK** [comment]
A good addition, but a fix texture is needed, we are waiting

**Comment by PssbleTrngle** [comment]
The missing textures have been added in version 1.7
