### ISSUE TITLE
Option to have emerald armor disabled when Actually Additions is detected

### ISSUE THREAD

**Issue by BugmanBugman** [PssbleTrngle/MiscIssues#9]
**Is your feature request related to a problem? Please describe.**
I have AA, which already adds emerald armor. I just don't want my game to be clogged with 2 types of armor
**Describe the solution you'd like**
A way to disable emerald armor
**Describe alternatives you've considered**

**Additional context**

**Comment by PssbleTrngle** [comment]
This is possible using the config file
